apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: solyntek
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          # Important : on utilise l'image buildée localement dans Minikube
          # imagePullPolicy doit être Never pour ne pas chercher sur Docker Hub
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE
         
