apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: solyntek
type: Opaque
stringData:
  # ⚠️  Remplacez ces valeurs par les vôtres avant d'appliquer
  JWT_SECRET: "aziz-linda"
  DATABASE: "mongodb://mongodb:27017/solyntek"
