apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: solyntek
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  # ClusterIP : le backend n'est accessible qu'en interne (via le frontend ou Ingress)
