apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: solyntek
spec:
  selector:
    app: frontend
  # NodePort permet à Minikube d'exposer le service directement sur un port de la VM
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
