apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: solyntek
spec:
  selector:
    app: frontend
  # LoadBalancer : sur EKS, AWS crée automatiquement un ALB avec une URL publique
  # (remplace le NodePort utilisé en local avec Minikube)
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
